// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import (
	pet_gateway "pethost/frameworks/database/gateways/pet_gateway"

	mock "github.com/stretchr/testify/mock"
)

// PetGateway is an autogenerated mock type for the PetGateway type
type PetGateway struct {
	mock.Mock
}

// Create provides a mock function with given fields: input
func (_m *PetGateway) Create(input pet_gateway.CreateInput) (string, error) {
	ret := _m.Called(input)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(pet_gateway.CreateInput) (string, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(pet_gateway.CreateInput) string); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(pet_gateway.CreateInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *PetGateway) Delete(id string) (bool, error) {
	ret := _m.Called(id)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *PetGateway) GetByID(id string) (*pet_gateway.GetByIDOutput, error) {
	ret := _m.Called(id)

	var r0 *pet_gateway.GetByIDOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*pet_gateway.GetByIDOutput, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *pet_gateway.GetByIDOutput); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pet_gateway.GetByIDOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: input
func (_m *PetGateway) List(input pet_gateway.ListInput) ([]pet_gateway.ListOutput, error) {
	ret := _m.Called(input)

	var r0 []pet_gateway.ListOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(pet_gateway.ListInput) ([]pet_gateway.ListOutput, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(pet_gateway.ListInput) []pet_gateway.ListOutput); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pet_gateway.ListOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(pet_gateway.ListInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Patch provides a mock function with given fields: filter, values
func (_m *PetGateway) Patch(filter pet_gateway.PatchFilter, values pet_gateway.PatchValues) (bool, error) {
	ret := _m.Called(filter, values)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(pet_gateway.PatchFilter, pet_gateway.PatchValues) (bool, error)); ok {
		return rf(filter, values)
	}
	if rf, ok := ret.Get(0).(func(pet_gateway.PatchFilter, pet_gateway.PatchValues) bool); ok {
		r0 = rf(filter, values)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(pet_gateway.PatchFilter, pet_gateway.PatchValues) error); ok {
		r1 = rf(filter, values)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPetGateway creates a new instance of PetGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPetGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *PetGateway {
	mock := &PetGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
