// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import (
	database "pethost/frameworks/database"

	mock "github.com/stretchr/testify/mock"

	schedule_gateway "pethost/frameworks/database/gateways/schedule_gateway"
)

// ScheduleGateway is an autogenerated mock type for the ScheduleGateway type
type ScheduleGateway struct {
	mock.Mock
}

// Create provides a mock function with given fields: input
func (_m *ScheduleGateway) Create(input schedule_gateway.CreateInput) (string, error) {
	ret := _m.Called(input)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(schedule_gateway.CreateInput) (string, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(schedule_gateway.CreateInput) string); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(schedule_gateway.CreateInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Paginate provides a mock function with given fields: filter, paginate
func (_m *ScheduleGateway) Paginate(filter schedule_gateway.PaginateFilter, paginate database.PaginateInput) (*schedule_gateway.PaginateOutput, error) {
	ret := _m.Called(filter, paginate)

	var r0 *schedule_gateway.PaginateOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(schedule_gateway.PaginateFilter, database.PaginateInput) (*schedule_gateway.PaginateOutput, error)); ok {
		return rf(filter, paginate)
	}
	if rf, ok := ret.Get(0).(func(schedule_gateway.PaginateFilter, database.PaginateInput) *schedule_gateway.PaginateOutput); ok {
		r0 = rf(filter, paginate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*schedule_gateway.PaginateOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(schedule_gateway.PaginateFilter, database.PaginateInput) error); ok {
		r1 = rf(filter, paginate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Patch provides a mock function with given fields: filter, values
func (_m *ScheduleGateway) Patch(filter schedule_gateway.PatchFilter, values schedule_gateway.PatchValues) (bool, error) {
	ret := _m.Called(filter, values)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(schedule_gateway.PatchFilter, schedule_gateway.PatchValues) (bool, error)); ok {
		return rf(filter, values)
	}
	if rf, ok := ret.Get(0).(func(schedule_gateway.PatchFilter, schedule_gateway.PatchValues) bool); ok {
		r0 = rf(filter, values)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(schedule_gateway.PatchFilter, schedule_gateway.PatchValues) error); ok {
		r1 = rf(filter, values)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewScheduleGateway creates a new instance of ScheduleGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewScheduleGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *ScheduleGateway {
	mock := &ScheduleGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
