// Code generated by mockery v2.33.2. DO NOT EDIT.

package mocks

import (
	gorm_adapter "pethost/frameworks/database/gorm"

	mock "github.com/stretchr/testify/mock"

	tutor_gateway "pethost/adapters/gateways/tutor_gateway"
)

// TutorGateway is an autogenerated mock type for the TutorGateway type
type TutorGateway struct {
	mock.Mock
}

// Create provides a mock function with given fields: input
func (_m *TutorGateway) Create(input tutor_gateway.CreateInput) (string, error) {
	ret := _m.Called(input)

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(tutor_gateway.CreateInput) (string, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(tutor_gateway.CreateInput) string); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(tutor_gateway.CreateInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *TutorGateway) Delete(id string) (bool, error) {
	ret := _m.Called(id)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: id
func (_m *TutorGateway) GetByID(id string) (*tutor_gateway.GetByIDOutput, error) {
	ret := _m.Called(id)

	var r0 *tutor_gateway.GetByIDOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*tutor_gateway.GetByIDOutput, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) *tutor_gateway.GetByIDOutput); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tutor_gateway.GetByIDOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: input
func (_m *TutorGateway) List(input tutor_gateway.ListInput) ([]tutor_gateway.ListOutput, error) {
	ret := _m.Called(input)

	var r0 []tutor_gateway.ListOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(tutor_gateway.ListInput) ([]tutor_gateway.ListOutput, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(tutor_gateway.ListInput) []tutor_gateway.ListOutput); ok {
		r0 = rf(input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tutor_gateway.ListOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(tutor_gateway.ListInput) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Paginate provides a mock function with given fields: filter, paginate
func (_m *TutorGateway) Paginate(filter tutor_gateway.PaginateFilter, paginate gorm_adapter.PaginateInput) (*tutor_gateway.PaginateOutput, error) {
	ret := _m.Called(filter, paginate)

	var r0 *tutor_gateway.PaginateOutput
	var r1 error
	if rf, ok := ret.Get(0).(func(tutor_gateway.PaginateFilter, gorm_adapter.PaginateInput) (*tutor_gateway.PaginateOutput, error)); ok {
		return rf(filter, paginate)
	}
	if rf, ok := ret.Get(0).(func(tutor_gateway.PaginateFilter, gorm_adapter.PaginateInput) *tutor_gateway.PaginateOutput); ok {
		r0 = rf(filter, paginate)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tutor_gateway.PaginateOutput)
		}
	}

	if rf, ok := ret.Get(1).(func(tutor_gateway.PaginateFilter, gorm_adapter.PaginateInput) error); ok {
		r1 = rf(filter, paginate)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Patch provides a mock function with given fields: filter, values
func (_m *TutorGateway) Patch(filter tutor_gateway.PatchFilter, values tutor_gateway.PatchValues) (bool, error) {
	ret := _m.Called(filter, values)

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(tutor_gateway.PatchFilter, tutor_gateway.PatchValues) (bool, error)); ok {
		return rf(filter, values)
	}
	if rf, ok := ret.Get(0).(func(tutor_gateway.PatchFilter, tutor_gateway.PatchValues) bool); ok {
		r0 = rf(filter, values)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(tutor_gateway.PatchFilter, tutor_gateway.PatchValues) error); ok {
		r1 = rf(filter, values)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTutorGateway creates a new instance of TutorGateway. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTutorGateway(t interface {
	mock.TestingT
	Cleanup(func())
}) *TutorGateway {
	mock := &TutorGateway{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
