name: Test

on:
  pull_request:
    branches:
      - main
      - develop
      - staging

jobs:
  Test:
    runs-on: ubuntu-latest
    container: golang:1.21.0

    services:
      postgres:
        image: postgres:13.4-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Fetch Repository
        uses: actions/checkout@v2

      - name: Setup Test
        env:
          PORT: 3000
        run: go run cmd/test_setup.go &

      - name: Run Test
        run: go test ./... -p 1 -v

      - name: Dispose
        run: kill $(jobs -p)
